# Generated by Django 3.2.12 on 2023-05-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_auto_20230520_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sechdule',
            name='rider',
        ),
        migrations.AddField(
            model_name='sechdule',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transport.driver'),
            preserve_default=False,
        ),
    ]
