# Generated by Django 4.2.1 on 2023-06-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_sechdule_friday_return_sechdule_monday_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='return_trip',
            field=models.BooleanField(default=False),
        ),
    ]
