# Generated by Django 3.2.12 on 2023-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_auto_20230520_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sechdule',
            name='friday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechdule',
            name='monday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechdule',
            name='saturday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechdule',
            name='sunday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechdule',
            name='thursday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechdule',
            name='tuesday',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sechdule',
            name='wednesday',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
